-- REB4LANCED Jokers Module
return function(REB4LANCED)
    local path = REB4LANCED.module_roots.base .. "jokers/"

    local function load_joker(name)
        assert(loadfile(path .. name .. ".lua"))()(REB4LANCED)
    end

    load_joker("atlas")
    load_joker("ace_in_hole")
    load_joker("report_card")
    load_joker("paint_bucket")
    load_joker("ceo")
    load_joker("nine_circles")
    load_joker("seven_leaf_clover")
    load_joker("pocket_aces")
    load_joker("fifth_avenue")
    load_joker("court_jester")
    load_joker("sweet_sixteen")
    load_joker("six_six_six")
    load_joker("four_corners")
    load_joker("satellite")
    load_joker("flower_pot")
    load_joker("delayed_gratification")
    load_joker("seeing_double")
    load_joker("smeared_joker")
    load_joker("mime")
    load_joker("baron")
    load_joker("mail_in_rebate")
    load_joker("marble_joker")
    load_joker("golden_ticket")
    load_joker("mad_joker")
    load_joker("crazy_joker")
    load_joker("droll_joker")
    load_joker("eight_ball")
    load_joker("bloodstone")
    load_joker("hanging_chad")
    load_joker("the_idol")
    load_joker("chicot")
    load_joker("space_joker")
    load_joker("vagabond")
    load_joker("madness")
    load_joker("rocket")
    load_joker("hit_the_road")
    load_joker("diet_cola")
    load_joker("constellation")
    load_joker("todo_list")
    load_joker("superposition")
    load_joker("bootstraps")
    load_joker("bull")
    load_joker("erosion")
    load_joker("throwback")
    load_joker("golden_joker")
    load_joker("matador")
    load_joker("yorick")
    load_joker("mr_bones")
    load_joker("seance")
    load_joker("campfire")
    load_joker("drunkard")
    load_joker("drivers_license")
    load_joker("merry_andy")
    load_joker("obelisk")
    load_joker("onyx_agate")
    load_joker("rough_gem")
    load_joker("masquerade")
end
